# Generated by Django 4.1.3 on 2022-12-04 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_answer_question_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0, message='Pass score must be greater than 0'), django.core.validators.MaxValueValidator(100, message='Pass score must be less than 100')]),
        ),
    ]
