# Generated by Django 4.1.3 on 2022-12-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='quizzes.question'),
        ),
    ]
