# Generated by Django 4.1.3 on 2022-12-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
