# Generated by Django 4.1.3 on 2022-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_testing_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='answers',
            field=models.ManyToManyField(blank=True, to='quizzes.answer'),
        ),
    ]
